apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: dev1
  namespace: datapower
spec:
  license:
    accept: true
    license: L-RJON-CCCP46
    use: nonproduction
  replicas: 2
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 4
      memory: 4Gi
    request:
      cpu: '4'
      memory: 4G
    limit:
      cpu: '4'
      memory: 4G
  version: 10.0-cd
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: admin-credentials
  domains:
  - name: "foo"
    dpApp:
      config:
      - "foobar-config"
