apiVersion: v1
kind: Service
metadata:
  name: dev1-service 
spec:
  selector:
    app.kubernetes.io/instance: cp4i-dev1
    app.kubernetes.io/name: datapower 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 
