kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dproute-ui
  namespace: datapower
spec:
  host: dev1-ivt-ui.mycluster-syd01-c3c-32x64-4c1a443ebaec2dc527b196dee1db66b5-0000.au-syd.containers.appdomain.cloud
  to:
    kind: Service
    name: dev1-service 
  port:
    targetPort: 9090 
  tls:
    termination: passthrough
